name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASS: ${{ secrets.SERVER_PASS }}
        run: |
          sshpass -p $PASS ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            sudo docker pull ghcr.io/${{ github.repository_owner }}/my-app:latest
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            sudo docker run -d --name my-app -p 80:3000 ghcr.io/${{ github.repository_owner }}/my-app:latest
          EOF